from __future__ import annotations

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_EMAIL = os.getenv("SMTP_EMAIL", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")


def send_result_email(
    to_email: str,
    question: str,
    status_log: str,
    full_log: str,
    answer: str,
    lean_code: str,
    verified: bool,
    stats: dict | None = None,
) -> bool:
    """Send research results via email with attached files. Returns True on success."""
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        print("SMTP not configured, skipping email")
        return False

    badge = "VERIFIED" if verified else "UNVERIFIED (best effort)"
    subject = f"VeriDeepResearch: {question[:60]}{'...' if len(question) > 60 else ''}"

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = f"VeriDeepResearch <{SMTP_EMAIL}>"
    msg["To"] = to_email

    # Format stats
    stats_html = ""
    if stats:
        elapsed = stats.get("elapsed_seconds", 0)
        mins = int(elapsed) // 60
        secs = int(elapsed) % 60
        time_str = f"{mins}m {secs}s" if mins else f"{secs}s"
        cost = stats.get("total_cost_usd", 0)
        inp = stats.get("total_input_tokens", 0)
        out = stats.get("total_output_tokens", 0)
        tool_counts = stats.get("tool_counts", {})

        tool_rows = ""
        for tool, count in sorted(tool_counts.items(), key=lambda x: -x[1]):
            tool_rows += f"<tr><td style='padding: 2px 12px 2px 0;'>{_escape(tool)}</td><td>{count}</td></tr>"

        stats_html = f"""
<h3>Stats</h3>
<table style="font-size: 14px; border-collapse: collapse;">
<tr><td style="padding: 2px 12px 2px 0;"><strong>Time</strong></td><td>{time_str}</td></tr>
<tr><td style="padding: 2px 12px 2px 0;"><strong>Cost</strong></td><td>${cost:.4f}</td></tr>
<tr><td style="padding: 2px 12px 2px 0;"><strong>Tokens</strong></td><td>{inp:,} in / {out:,} out</td></tr>
</table>
<br>
<table style="font-size: 13px; border-collapse: collapse;">
<tr><th style="text-align: left; padding: 2px 12px 2px 0;">Tool</th><th style="text-align: left;">Calls</th></tr>
{tool_rows}
</table>
"""

    # HTML body
    html = f"""\
<html>
<body style="font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
<h2>VeriDeepResearch Results</h2>

<p><strong>Question:</strong> {_escape(question)}</p>
<p><strong>Status:</strong> <span style="color: {'green' if verified else 'orange'}; font-weight: bold;">{badge}</span></p>

{stats_html}

<hr>

<h3>Answer</h3>
<div style="background: #f8f9fa; padding: 16px; border-radius: 8px; margin: 12px 0;">
{_escape(answer).replace(chr(10), '<br>')}
</div>

<h3>Lean 4 Code ({badge})</h3>
<pre style="background: #1e1e1e; color: #d4d4d4; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px;">
{_escape(lean_code)}
</pre>

<details>
<summary><strong>Status Log</strong></summary>
<pre style="background: #f0f0f0; padding: 12px; border-radius: 8px; font-size: 12px; white-space: pre-wrap;">
{_escape(status_log)}
</pre>
</details>

<hr>
<p style="color: #666; font-size: 12px;">
Full research log and Lean code attached as files.<br>
Generated by <a href="https://vilin97-verideepresearch.hf.space">VeriDeepResearch</a>.
All Lean code checked with Axle (Lean 4.28.0 + Mathlib).
</p>
</body>
</html>
"""
    body = MIMEMultipart("alternative")
    body.attach(MIMEText(f"Question: {question}\nStatus: {badge}\n\nAnswer:\n{answer}\n\nSee attached files for Lean code and full research log.", "plain"))
    body.attach(MIMEText(html, "html"))
    msg.attach(body)

    # Attachment 1: Lean code (.lean file)
    if lean_code.strip():
        lean_attachment = MIMEBase("application", "octet-stream")
        lean_attachment.set_payload(lean_code.encode("utf-8"))
        encoders.encode_base64(lean_attachment)
        lean_attachment.add_header(
            "Content-Disposition",
            "attachment",
            filename="proof.lean",
        )
        msg.attach(lean_attachment)

    # Attachment 2: Full research log (.md file)
    if full_log.strip():
        log_attachment = MIMEBase("application", "octet-stream")
        log_content = f"# VeriDeepResearch Full Log\n\n**Question:** {question}\n**Status:** {badge}\n\n---\n\n{full_log}"
        log_attachment.set_payload(log_content.encode("utf-8"))
        encoders.encode_base64(log_attachment)
        log_attachment.add_header(
            "Content-Disposition",
            "attachment",
            filename="research_log.md",
        )
        msg.attach(log_attachment)

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.sendmail(SMTP_EMAIL, to_email, msg.as_string())
        print(f"Email sent to {to_email}")
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False


def _escape(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
