from __future__ import annotations

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_EMAIL = os.getenv("SMTP_EMAIL", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")


def send_result_email(
    to_email: str,
    question: str,
    status_log: str,
    answer: str,
    lean_code: str,
    verified: bool,
) -> bool:
    """Send research results via email. Returns True on success."""
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        print("SMTP not configured, skipping email")
        return False

    badge = "VERIFIED" if verified else "UNVERIFIED (best effort)"
    subject = f"VeriDeepResearch: {question[:60]}{'...' if len(question) > 60 else ''}"

    # Build HTML email
    html = f"""\
<html>
<body style="font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
<h2>VeriDeepResearch Results</h2>

<p><strong>Question:</strong> {_escape(question)}</p>
<p><strong>Status:</strong> <span style="color: {'green' if verified else 'orange'}; font-weight: bold;">{badge}</span></p>

<hr>

<h3>Answer</h3>
<div style="background: #f8f9fa; padding: 16px; border-radius: 8px; margin: 12px 0;">
{_escape(answer).replace(chr(10), '<br>')}
</div>

<h3>Lean 4 Code ({badge})</h3>
<pre style="background: #1e1e1e; color: #d4d4d4; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px;">
{_escape(lean_code)}
</pre>

<details>
<summary><strong>Research Log</strong></summary>
<pre style="background: #f0f0f0; padding: 12px; border-radius: 8px; font-size: 12px; white-space: pre-wrap;">
{_escape(status_log)}
</pre>
</details>

<hr>
<p style="color: #666; font-size: 12px;">
Generated by <a href="https://vilin97-verideepresearch.hf.space">VeriDeepResearch</a>.
All Lean code checked with Axle (Lean 4.28.0 + Mathlib).
</p>
</body>
</html>
"""

    # Plain text fallback
    text = f"""\
VeriDeepResearch Results
========================

Question: {question}
Status: {badge}

Answer:
{answer}

Lean 4 Code:
{lean_code}

Research Log:
{status_log}
"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"VeriDeepResearch <{SMTP_EMAIL}>"
    msg["To"] = to_email
    msg.attach(MIMEText(text, "plain"))
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.sendmail(SMTP_EMAIL, to_email, msg.as_string())
        print(f"Email sent to {to_email}")
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False


def _escape(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
